<img src="../images/logo_VORTEX.png" width="200" height="auto" alt="Company Logo">

| Project| Authors           | Company                                 | Year | Chapter |
|--------|-------------------|-----------------------------------------|------|---------|
| Pywind | Oriol L & Arnau T | [Vortex FdC](https://www.vortexfdc.com) | 2025 | 1       |

# Chapter 1: Loading NetCDF

_Overview:_

This script reads meteorological **NetCDF data (.nc)** and uses functions to load and show the file structure and a quick overview.

> What are *NetCDF* files? Read our Blog post [here](https://vortexfdc.com/blog/what-is-a-netcdf-file/).

- Measurements (NetCDF) - Contains single height with limited variables.
- Vortex NetCDF - NetCDF file format with multiple heights and variables.

_Downloads Data Here:_
- [Froya Data Pack](http://download.vortexfdc.com/froya.zip) 

- [VortexFDC/pywind] https://github.com/VortexFDC/pywind/tree/main

_Data Storage:_

The acquired data is stored in two data structures for comparison and analysis:
- Xarray Dataset
- Pandas DataFrame

_Objective:_

- To understand the variance in data storage when using Xarray and Pandas.
- Utilize the basic commands to make a quick overview of the loaded data; e.g. `describe()` and `head()`.



### Import Libraries



In [3]:
import xarray as xr
import numpy as np
import pandas as pd
import os


### Define Paths and Site


In [6]:
SITE = 'froya'
pwd = os.getcwd()
base_path = os.path.join(pwd, '../data')

measurements_netcdf = os.path.join(base_path, f'{SITE}/measurements/obs.nc')
vortex_netcdf = os.path.join(base_path, f'{SITE}/vortex/SERIE/vortex.serie.era5.utc0.nc')

print(f'Measurements NetCDF: {measurements_netcdf}')
print(f'Vortex NetCDF: {vortex_netcdf}')

Measurements NetCDF: C:\Users\U S E R\Anaconda\Portfolio\Python\Pywind\notebooks\../data\froya/measurements/obs.nc
Vortex NetCDF: C:\Users\U S E R\Anaconda\Portfolio\Python\Pywind\notebooks\../data\froya/vortex/SERIE/vortex.serie.era5.utc0.nc


### Read NetCDF functions


In [9]:
# Read measurements NetCDF
ds_measurements = xr.open_dataset(measurements_netcdf)
ds_measurements

<xarray.Dataset>
Dimensions:  (lat: 1, lon: 1, lev: 5, time: 171895)
Coordinates:
  * lat      (lat) float64 63.67
  * lon      (lon) float64 8.343
  * lev      (lev) float64 10.0 25.0 40.0 70.0 100.0
  * time     (time) datetime64[ns] 2009-11-18T13:50:00 ... 2014-12-07T07:40:00
Data variables:
    M        (lat, lon, lev, time) float64 ...
    Dir      (lat, lon, lev, time) float64 ...
Attributes:
    description:  Wind Speed (module velocity)
    long_name:    Wind speed
    units:        m/s
    lag:          -7

In [13]:
# Read Vortex NetCDF
ds_vortex = xr.open_dataset(vortex_netcdf)
ds_vortex

<xarray.Dataset>
Dimensions:  (lon: 1, lat: 1, lev: 10, time: 176424)
Coordinates:
  * lon      (lon) float32 8.342
  * lat      (lat) float32 63.67
  * lev      (lev) float32 8.0 28.0 52.0 80.0 111.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 2004-01-01 ... 2024-02-15T23:00:00
Data variables:
    M        (lev, time, lat, lon) float32 ...
    Dir      (lev, time, lat, lon) float32 ...
    T        (lev, time, lat, lon) float32 ...
    D        (lev, time, lat, lon) float32 ...
    P        (lev, time, lat, lon) float32 ...
    RH       (lev, time, lat, lon) float32 ...
    RI       (time, lev, lat, lon) float64 ...
Attributes:
    Reanalysis:            ERA5
    Origin:                VORTEX SL
    Product:               SERIES
    HorizontalResolution:  3km
    Produced:              2024-04-11 11:09:26
    WorkID:                1235817
    history:               Vortex processed time serie from era5-wrf downscal...
    NCO:                   netCDF Operators version 5.0.6 (Homepage = http://...

We can observe the typical structure of **Xarray** data. When multiple variables are present, it is referred to as a *Dataset*. If there is only a single variable, it is called a *DataArray*. 

>Let's explore the various information available within these structures.

In [16]:
# Dataset coordinates
ds_vortex.coords

Coordinates:
  * lon      (lon) float32 8.342
  * lat      (lat) float32 63.67
  * lev      (lev) float32 8.0 28.0 52.0 80.0 111.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 2004-01-01 ... 2024-02-15T23:00:00

In [18]:
# Dataset dimensions
ds_vortex.dims

Frozen({'lon': 1, 'lat': 1, 'lev': 10, 'time': 176424})

The **metadata** is called *attributes*. It is a dictionary in Python.

In [21]:
# Dataset attributes
ds_vortex.attrs

{'Reanalysis': 'ERA5',
 'Origin': 'VORTEX SL',
 'Product': 'SERIES',
 'HorizontalResolution': '3km',
 'Produced': '2024-04-11 11:09:26',
 'WorkID': 1235817,
 'history': 'Vortex processed time serie from era5-wrf downscalling',
 'NCO': 'netCDF Operators version 5.0.6 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)'}

And the data variables with its dimensions and data type.

In [24]:
ds_vortex.data_vars

Data variables:
    M        (lev, time, lat, lon) float32 ...
    Dir      (lev, time, lat, lon) float32 ...
    T        (lev, time, lat, lon) float32 ...
    D        (lev, time, lat, lon) float32 ...
    P        (lev, time, lat, lon) float32 ...
    RH       (lev, time, lat, lon) float32 ...
    RI       (time, lev, lat, lon) float64 ...

Each var has attributes, with metadata information.

In [27]:
ds_vortex.variables['M'].attrs

{'description': 'Wind Speed (module velocity)',
 'long_name': 'Wind speed',
 'units': 'm/s'}

The data for each variable can also be accessed individually, retaining the associated coordinates and attributes. Each variable may have different dimensions and corresponding coordinates

In [30]:
ds_vortex['M']

<xarray.DataArray 'M' (lev: 10, time: 176424, lat: 1, lon: 1)>
[1764240 values with dtype=float32]
Coordinates:
  * lon      (lon) float32 8.342
  * lat      (lat) float32 63.67
  * lev      (lev) float32 8.0 28.0 52.0 80.0 111.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 2004-01-01 ... 2024-02-15T23:00:00
Attributes:
    description:  Wind Speed (module velocity)
    long_name:    Wind speed
    units:        m/s

In [32]:
ds_vortex['M']['lev']

<xarray.DataArray 'lev' (lev: 10)>
array([  8.,  28.,  52.,  80., 111., 145., 182., 220., 263., 330.],
      dtype=float32)
Coordinates:
  * lev      (lev) float32 8.0 28.0 52.0 80.0 111.0 ... 182.0 220.0 263.0 330.0
Attributes:
    units:      metres
    long_name:  Level

We have a DataArray when dealing with a single 'column' of data.

In [35]:
type(ds_vortex['M'])

xarray.core.dataarray.DataArray

To get just the values in a Numpy Array format. This is what we would say a common array.

In [38]:
type(ds_vortex['M'].values)

numpy.ndarray

In [40]:
ds_vortex['M'].values

array([[[[ 4.4713726]],

        [[ 4.1169853]],

        [[ 4.61843  ]],

        ...,

        [[ 6.359386 ]],

        [[ 5.7004547]],

        [[ 4.4155455]]],


       [[[ 4.538038 ]],

        [[ 4.203529 ]],

        [[ 4.7278867]],

        ...,

        [[ 6.6354218]],

        [[ 5.8938055]],

        [[ 4.5033   ]]],


       [[[ 4.553902 ]],

        [[ 4.244887 ]],

        [[ 4.783167 ]],

        ...,

        [[ 6.721409 ]],

        [[ 5.9447217]],

        [[ 4.5229263]]],


       ...,


       [[[ 7.634639 ]],

        [[ 6.5912933]],

        [[ 7.0861382]],

        ...,

        [[ 6.487186 ]],

        [[ 4.5752106]],

        [[ 3.7386734]]],


       [[[10.105934 ]],

        [[ 9.102782 ]],

        [[ 9.344037 ]],

        ...,

        [[ 5.3326015]],

        [[ 3.9022276]],

        [[ 4.1259403]]],


       [[[ 9.446582 ]],

        [[ 9.830642 ]],

        [[ 9.356058 ]],

        ...,

        [[ 3.5960932]],

        [[ 3.0247219]],

        [[ 3.6984

The array still has some dimensions. We can remove single value dimensions using the squeeze() call for the object. See how it converts after aplying it.

In [43]:
print(ds_vortex['M'].shape)
print(ds_vortex['M'].squeeze().values)
print(ds_vortex['M'].squeeze().shape)

(10, 176424, 1, 1)
[[ 4.4713726  4.1169853  4.61843   ...  6.359386   5.7004547  4.4155455]
 [ 4.538038   4.203529   4.7278867 ...  6.6354218  5.8938055  4.5033   ]
 [ 4.553902   4.244887   4.783167  ...  6.721409   5.9447217  4.5229263]
 ...
 [ 7.634639   6.5912933  7.0861382 ...  6.487186   4.5752106  3.7386734]
 [10.105934   9.102782   9.344037  ...  5.3326015  3.9022276  4.1259403]
 [ 9.446582   9.830642   9.356058  ...  3.5960932  3.0247219  3.6984565]]
(10, 176424)


We can access to the values refering by each dimension indexes. ":" refers to start:end considering all in this case. You can use indexes before and after the ":".
In this case we access:
- first 24 values for the 0 level.(one day time series at lev=0)
- first value of all levels. (shear at this timestamp)

In [45]:
print(ds_vortex['M'].squeeze().values[0:12,0])
print(ds_vortex['M'].squeeze().values[0,:])

[ 4.4713726  4.538038   4.553902   4.5563645  4.566679   4.565929
  5.3193936  7.634639  10.105934   9.446582 ]
[4.4713726 4.1169853 4.61843   ... 6.359386  5.7004547 4.4155455]


### Convert to Pandas DataFrame and inspect

Pandas function `head()` shows the first values.

In [48]:
df_measurements = ds_measurements.to_dataframe()
print(type(df_measurements))
df_measurements.head()

<class 'pandas.core.frame.DataFrame'>


M    Dir
lat      lon     lev  time                             
63.66638 8.34251 10.0 2009-11-18 13:50:00  2.560  111.5
                      2009-11-18 14:00:00  2.943   99.5
                      2009-11-18 14:10:00  3.125   91.5
                      2009-11-18 14:20:00  3.654   89.0
                      2009-11-18 14:30:00  3.628   93.5

In [50]:
df_measurements = ds_measurements.to_dataframe().reset_index()
print(type(df_measurements))
df_measurements.head()

<class 'pandas.core.frame.DataFrame'>


lat      lon   lev                time      M    Dir
0  63.66638  8.34251  10.0 2009-11-18 13:50:00  2.560  111.5
1  63.66638  8.34251  10.0 2009-11-18 14:00:00  2.943   99.5
2  63.66638  8.34251  10.0 2009-11-18 14:10:00  3.125   91.5
3  63.66638  8.34251  10.0 2009-11-18 14:20:00  3.654   89.0
4  63.66638  8.34251  10.0 2009-11-18 14:30:00  3.628   93.5

In [52]:
df_vortex = ds_vortex.to_dataframe()
df_vortex.head()

M         Dir         T  \
lon      lat       lev time                                                  
8.342499 63.666386 8.0 2004-01-01 00:00:00  4.471373  149.532516 -0.700592   
                       2004-01-01 01:00:00  4.116985  158.352905 -0.560852   
                       2004-01-01 02:00:00  4.618430  164.658569 -0.550995   
                       2004-01-01 03:00:00  4.449509  153.565109 -0.627899   
                       2004-01-01 04:00:00  4.555139  141.756287 -0.690002   

                                              D    P   RH   RI  
lon      lat       lev time                                     
8.342499 63.666386 8.0 2004-01-01 00:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 01:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 02:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 03:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 04:00:00  0.0  0.0  0.0  0.0

In [54]:
df_vortex = ds_vortex.to_dataframe().reset_index()
df_vortex.head()

lon        lat  lev                time         M         Dir  \
0  8.342499  63.666386  8.0 2004-01-01 00:00:00  4.471373  149.532516   
1  8.342499  63.666386  8.0 2004-01-01 01:00:00  4.116985  158.352905   
2  8.342499  63.666386  8.0 2004-01-01 02:00:00  4.618430  164.658569   
3  8.342499  63.666386  8.0 2004-01-01 03:00:00  4.449509  153.565109   
4  8.342499  63.666386  8.0 2004-01-01 04:00:00  4.555139  141.756287   

          T    D    P   RH   RI  
0 -0.700592  0.0  0.0  0.0  0.0  
1 -0.560852  0.0  0.0  0.0  0.0  
2 -0.550995  0.0  0.0  0.0  0.0  
3 -0.627899  0.0  0.0  0.0  0.0  
4 -0.690002  0.0  0.0  0.0  0.0

### Interpolate to the same height

We have multiple levels in `ds_vortex`, so we need to interpolate the data to match the height levels in `ds_measurements`.

In [58]:
max_height = ds_measurements.squeeze().coords['lev'].max().values
min_height = ds_measurements.squeeze().coords['lev'].min().values
max_height_v = ds_vortex.squeeze().coords['lev'].max().values
min_height_v = ds_vortex.squeeze().coords['lev'].min().values

print(f'Measurements heights = {ds_measurements.squeeze().coords['lev'].values}')
print(f'Min height in measurements = {min_height}')
print(f'Max height in measurements = {max_height}\n')

print(f'Vortex heights = {ds_vortex.squeeze().coords['lev'].values}')
print(f'Min height in vortex = {min_height_v}')
print(f'Max height in vortex = {max_height_v}')

Measurements heights = [ 10.  25.  40.  70. 100.]
Min height in measurements = 10.0
Max height in measurements = 100.0

Vortex heights = [  8.  28.  52.  80. 111. 145. 182. 220. 263. 330.]
Min height in vortex = 8.0
Max height in vortex = 330.0


In [60]:
ds_vortex = ds_vortex.interp(lev=max_height)
ds_vortex

<xarray.Dataset>
Dimensions:  (lon: 1, lat: 1, time: 176424)
Coordinates:
  * lon      (lon) float32 8.342
  * lat      (lat) float32 63.67
  * time     (time) datetime64[ns] 2004-01-01 ... 2024-02-15T23:00:00
    lev      float64 100.0
Data variables:
    M        (time, lat, lon) float64 4.563 4.306 4.867 ... 6.786 5.965 4.472
    Dir      (time, lat, lon) float64 153.9 161.8 166.3 ... 107.9 113.3 122.2
    T        (time, lat, lon) float64 -1.842 -1.707 -1.709 ... 0.3004 0.2648
    D        (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    P        (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    RH       (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    RI       (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
Attributes:
    Reanalysis:            ERA5
    Origin:                VORTEX SL
    Product:               SERIES
    HorizontalResolution:  3km
    Produced:              2024-04-11 11:09:26
    WorkID:                1235817
    history:               Vortex processed time serie from era5-wrf downscal...
    NCO:                   netCDF Operators version 5.0.6 (Homepage = http://...

Although the coordinate **lev** is still available, it is no longer a dimension for any variable. (Check for missing *lev in the coordinates.)

In [62]:
df_vortex = ds_vortex.to_dataframe()
df_vortex.head()

M         Dir         T    D  \
lon      lat       time                                                       
8.342499 63.666386 2004-01-01 00:00:00  4.563019  153.946593 -1.842128  0.0   
                   2004-01-01 01:00:00  4.306192  161.784135 -1.706702  0.0   
                   2004-01-01 02:00:00  4.867352  166.291114 -1.708884  0.0   
                   2004-01-01 03:00:00  4.656087  156.031946 -1.782793  0.0   
                   2004-01-01 04:00:00  4.717631  145.335684 -1.851102  0.0   

                                          P   RH   RI    lev  
lon      lat       time                                       
8.342499 63.666386 2004-01-01 00:00:00  0.0  0.0  0.0  100.0  
                   2004-01-01 01:00:00  0.0  0.0  0.0  100.0  
                   2004-01-01 02:00:00  0.0  0.0  0.0  100.0  
                   2004-01-01 03:00:00  0.0  0.0  0.0  100.0  
                   2004-01-01 04:00:00  0.0  0.0  0.0  100.0

### Now we can compare statistics for M and Dir

In [64]:
# Rename direction coordinate
if 'Dir' not in ds_vortex.data_vars and 'D' in ds_vortex.data_vars:
    ds_vortex = ds_vortex.rename({'D':'Dir'})
    
# Drop coordinates lat  and lon  and dimensions of ds_vortex
ds_vortex = ds_vortex.squeeze().reset_coords(drop=True)
ds_measurements = ds_measurements.squeeze().reset_coords(drop=True)

Notebooks allow for a better display format:

In [67]:
from IPython.display import display

print('Vortex')
display(ds_vortex[['M', 'Dir']].to_dataframe().describe())
print('\n')

print('Measurement')
display(ds_measurements[['M', 'Dir']].to_dataframe().describe())

Vortex


M            Dir
count  176424.000000  176424.000000
mean        8.428640     183.069491
std         4.769399      89.357324
min         0.085077       0.024005
25%         4.861127     111.684096
50%         7.620304     194.410668
75%        11.044065     247.968690
max        34.701458     359.953259



Measurement


M            Dir
count  859475.000000  859475.000000
mean        7.271270     174.898990
std         4.357101      96.383515
min         0.079500       0.000000
25%         4.105500      91.000000
50%         6.296000     189.500000
75%         9.484000     249.000000
max        36.103000     360.000000

### Thank you for completing this Notebook! 
### *Other references available upon request.*

You now can:

- Open NetCdf using **Xarray** python library.
- Inspect the metadata.
- Rename variables.
- Interpolate within a dimension.
- Convert to **Pandas** DataFrames.
- Have a quick overview of the data using `head()` and `describe()` Pandas functions.

**Don't hesitate to [contact us](https://vortexfdc.com/contact/) for any questions and information.**

## Change Log


| Date (YYYY-MM-DD) | Version | Changed By | Change Description                         |
|-------------------|---------|------------|--------------------------------------------|
| 2023-02-25        | 0.0     | Oriol      | Notebook creation                          |
| 2023-09-28        | 0.2     | Arnau      | Comment sections & add complementary plots |
| 2023-10-02        | 0.3     | Arnau      | Improve notebook visualization             |
| 2024-02-06        | 0.4     | Oriol      | Vortexpy compatibility                     |
| 2024-11-12        | 0.4.1   | Oriol      | Review                                     |


<hr>

## <h3 align="center"> © Vortex F.d.C. 2024. All rights reserved. <h3/>